### ISSUE TITLE
Can 5.0 above supported?

### ISSUE THREAD

**Issue by rdmclin2** [Rhapsod/sapienz#10]
It seems that the motifcore.jar in my nexus5 with 5.0.1 Lolipop cannot properly run. 

The printout shows that monkey Switch action has been generated successfully, but the action is not executed properly.
```
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=org.jtb.alogcat/.LogActivity;end
:Sending rotation degree=0, persist=false
```

A successful switch action should be as follows:
```
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=org.jtb.alogcat/.LogActivity;end
    // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.jtb.alogcat/.LogActivity } in package org.jtb.alogcat
```

Do you know where the problem is ?

**Comment by DavidWangChen** [comment]
您好！孟，Sapienz工具你当时运行到哪里卡住了，我也在尝试重复这个程序。
希望能得到你的任何回复。
谢谢了。

**Comment by hxtkyne** [comment]
Do you solve the problem? Can anyone help me? Really thanks

**Comment by rdmclin2** [comment]
Sorry, i have forgotten about it, it has been quite a long time.
