### ISSUE TITLE
java.lang.exception

### ISSUE THREAD

**Issue by shishangx** [Rhapsod/sapienz#5]
Hi,
when i run the tools, the system print the below info:
`//   10: 3.0%
//   11: 10.0%
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.example.android.notepad/.NotesList;end
:Sending rotation degree=0, persist=false
java.lang.Exception
    at android.os.Process.killProcess(Process.java:1255)
    at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:125)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
... Finish generating a sequence
`
what happened?could you pls help me..

**Comment by Rhapsod** [comment]
Hi, Sapienz currently works for Android 4.4, could you check which API level are you running on?

**Comment by shishangx** [comment]
Thank you for your instruments, i ran the sapienz for app test at the android 6.0 device.
so,could you have the plan for new versions and support more android versions?

**Comment by Rhapsod** [comment]
We have the plan but we may not provide an update recently. I will let you know once we have an update on the artefact. 
Thanks. Now I will close this issue.
