### ISSUE TITLE
rm failed for /mnt/sdcard/_strings.xml, No such file or directory

### ISSUE THREAD

**Issue by staleejunho** [Rhapsod/sapienz#6]
List of devices attached 
emulator-5554	device
370fe160	device

I: Using Apktool 2.0.2 on CJmall.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
rm failed for /mnt/sdcard/_strings.xml, No such file or directory
370 KB/s (38880 bytes in 0.102s)
rm failed for /mnt/sdcard/bugreport.crash, No such file or directory

**Comment by Rhapsod** [comment]
Hi Thanks for the feedback.
The 'rm failed' warning won't cause any problem (as we haven't started testing yet). You can ignore this.
